social network app/app/urls.py
from django.urls import path

from . import views
app_name = 'network'

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
  
    path("newpost", views.newpost, name="newpost"),

    path("profile/<str:user>",views.profile,name="profile"),
    path("profile/<str:user>/<str:category>",views.profile,name="profile"),
    path("profile/<str:user>/section/<str:category>",views.profile_section,name="profile_section"),

    path("network",views.network,name="network"),
    path("network/<str:request_type>",views.network,name="network"),
    path("network/section/<str:section>",views.network_section,name="network_section"),
   
    path("editpost/<int:post_id>",views.edit_post,name="editpost"),
    path("profile/<str:user>/editpost/<int:post_id>",views.edit_post,name="editpost"),

    path("savepost/<int:post_id>/<str:content>",views.save_post,name="save_post"),
    path("profile/<str:user>/savepost/<int:post_id>/<str:content>",views.save_post,name="save_post"),
    
    path("profile/<str:user>/deletepost/<int:post_id>", views.delete_post, name="delete_post"),
    path("deletepost/<int:post_id>", views.delete_post, name="delete_post"),
    
    path("like/<int:post_id>", views.update_like, name="update_like"),
    path("profile/<str:user>/like/<int:post_id>", views.update_like, name="update_like"),
    
    path("connect/<str:user>",views.connect,name="connect"),
    path("connect",views.connect,name="connect"),

    path("following",views.following_posts,name="following_posts"),
    

]

social network app/app/templates/network/following.html
{% extends "network/layout.html" %}

{% block title %}
    Following
{% endblock %}
{% load static %}

{% block body %}
<section>
    <article class="result">
        <div class="message">

        </div>
        <div class="container-allpost">
            {% if allposts.has_other_pages %} 
                <ul class="pagination justify-content-center">
                {% if allposts.had_previous %} 
                    <li class="page-item"><a class="page-link" href="?page={{ allposts.previous_page_number }}">Previous</a></li>
                {% else %} 
                    <li class="page-item disabled"><span class="page-link">Previous</span></li>
                {% endif %} 
                {% for i in allposts.paginator.page_range %} 
                    {% if allposts.number == i %} 
                        <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>    
                    {% else %} 
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %} 
                {% endfor %} 
                {% if allposts.has_next %} 
                    <li class="page-item"><a class="page-link" href="?page={{ allposts.next_page_number }}">Next</a></li>
                {% else %}
                    <li class="disabled page-item"><span class="page-link">Next</span></li>
                {% endif %}    
            </ul>
            {% endif %}
                <section>
                    <article id ="showposts">
                       
                        {% for post in allposts %}
                                
                            <div class = "card" >
                                <span>
                                   

                                    <h2 id ="post_userid" class="card-title">{{post.user_id}}</h2>
                                    <h3 id ="post_content">{{post.contents}}</h3>
                                    <h4 id ="post_dateandtime">{{post.date_and_time}}</h4>
                                    <h4 id ='num_likes_{{post.id}}' class='like'>{{post.num_of_likes}} like(s)</h4>
            
     
                                    { % if post.num_of_likes > 0 and post_liked_ids|length  and post.id in post_liked_ids %}
                                        <button id ="like"  value ="{{post.id}}" ><i class="fa fa-heart" style = "color:#f7786b"></i></button>
                                    {% else %}
                                        <button id ="like" value ="{{post.id}}" ><i class="fa fa-heart" style = "color:#b0aac0"></i></button>
                                    {% endif %}
        
        
                                    
                                   
                                </span>
                            </div>
                        {% empty %}
                
                        <h5 class="notfound text-center">You are following no one</h5>
                                
                        {% endfor %}
                        
                    </article>
                </section>
             
                
        
            
                {% if allposts.has_other_pages %}
                <ul class="pagination justify-content-center">
                    {% if allposts.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ allposts.previous_page_number }}">Previous</a></li>
                    {% else %}
                    <li class="page-item disabled"><span class="page-link">Previous</span></li>
                    {% endif %}
                    {% for i in allposts.paginator.page_range %}
                        {% if allposts.number == i %}
                            <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if allposts.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ allposts.next_page_number }}">Next</a></li>
                    {% else %}
                    <li class="disabled page-item"><span class="page-link">Next</span></li>
                    {% endif %}
                </ul>
            {% endif %}
            </div>
    
    
        </article>
    </section>
    <script type ="text/javascript" src="{% static 'functions.js' %}"></script>
    <script type ="text/javascript" src="{% static 'index.js' %}"></script>
    {% endblock %}

social network app/app/templates/network/index.html
{% extends "network/layout.html" %}

{% block title %}
    Posts
{% endblock %}
{% load static %}
{% block body %}
    <!-- 
    1. display all the posts with pagination
    2. user can like any post 
    3. user can edit their own post
    4. user can delete their own post 
    -->
<script type ="text/javascript" src="{% static 'util.js' %}"></script>


    <div class = "container-allpost"  >
        <form action="{% url 'network:newpost' %}" method ="POST">
            {% csrf_token %}    
        <div id ="newpost-button">

            <h1>Whats on your mind?
            <span> <button type = "submit" name ="newpost" id ="newpost" class ="btn btn-primary">Write here</button></span>
        </h1>
        </div> 
        </form> 
        {% if allposts.has_other_pages %}
        <ul class="pagination justify-content-center">
            {% if allposts.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ allposts.previous_page_number }}">Previous</a></li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">Previous</span></li>
            {% endif %}
            {% for i in allposts.paginator.page_range %}
                {% if allposts.number == i %}
                    <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if allposts.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ allposts.next_page_number }}">Next</a></li>
            {% else %}
            <li class="disabled page-item"><span class="page-link">Next</span></li>
            {% endif %}
        </ul>
    {% endif %}
        <section>
            <article id ="showposts">
               
                {% for post in allposts %}
                        
                    <div class = "card" id = eachpost_{{post.id}} >
                        <span>
                           
                            {% with post_userId=post.user_id_id %}

                                <!-- user can delete and edit only their own post -->
                                <button id = "edit" name ="edit"type="submit" value= {{post.id}} onclick = "edit_post('{{ post.id }}','{{ post_username }}')"><i class="fa fa-edit" style = "color:#f7786b"></i></button>
                               
                            
                                <button id="delete" name = "delete" type = "submit" value= {{post.id}} onclick = "delete_post('{{ post.id }}')"  ><i class="fa fa-trash" style = "color:#f7786b"></i></button>
                               
                             

                            {%endwith%}
                            
                            
                            <h2 id ="post_userid" class="card-title">{{post.user_id}}</h2>
                            <h3 id ="post_content">{{post.contents}}</h3>
                            <h4 id ="post_dateandtime">{{post.date_and_time}}</h4>
                            <h4 id ='num_likes_{{post.id}}' class='like'>{{post.num_of_likes}} like(s)</h4>
    
                           
                            {% if post.num_of_likes > 0 and post_liked_ids|length  and post.id in post_liked_ids %}
                                <button id ="like"  value ="{{post.id}}" ><i class="fa fa-heart" style = "color:#f7786b"></i></button>
                            {% else %}
                                <button id ="like" value ="{{post.id}}" ><i class="fa fa-heart" style = "color:#b0aac0"></i></button>
                            {% endif %}

                            


                            
                         
                        </span>
                    </div>
                {% empty %}
        
                <h5 class ="notfound text-center" id= "nopostfound">Be first to write a new post!</h5>
                        
                {% endfor %}
                
            </article>
        </section>
     
        

    
        {% if allposts.has_other_pages %}
        <ul class="pagination justify-content-center">
            {% if allposts.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ allposts.previous_page_number }}">Previous</a></li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">Previous</span></li>
            {% endif %}
            {% for i in allposts.paginator.page_range %}
                {% if allposts.number == i %}
                    <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if allposts.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ allposts.next_page_number }}">Next</a></li>
            {% else %}
            <li class="disabled page-item"><span class="page-link">Next</span></li>
            {% endif %}
        </ul>
    {% endif %}
    </div>
    <script type ="text/javascript" src="{% static 'functions.js' %}"></script>
    <script type ="text/javascript" src="{% static 'index.js' %}"></script>

    
        

  
{% endblock %}

social network app/app/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %} Network {% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
    </head>
    <body>


        <nav class="navbar navbar-expand-lg navbar-light bg-light flex-row d-flex bd-highlight mb-3" id="main-nav">
            <a class="navbar-brand text-monospace" id = "logo" href="{% url 'network:index' %}">Network</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    
                    <li class="nav-item">
 
                        <a class="nav-link" href="{% url 'network:profile' user=user.username category='myposts' %}"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'network:index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href=" {% url 'network:following_posts' %}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="body">

           <script>
               var csrfToken = "{{csrf_token}}"
                const username ="{{ user.username }}"
        </script>
            {% block body %}
            {% endblock %}
        </div>

    </body>
    <footer id ="footer">
      
        <small> &#169; Created by Justin Milner </small>
   </footer>
</html>

social network app/app/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}



<div class = "card" id = "signIn">
    <fieldset>
        <legend class="card-body"> 
            <h2 class="card-title">
                <div>

                        Don't have an account? 

                    <span>
                        <a href="{% url 'network:register' %}" class = "btn-link" id="createaccount">Register here.</a> 
                    </span>
                </div>
            </h2>
        </legend>
    </fieldset>

    <fieldset class="card-body">
        <legend >
            <h2 class="card-title">Sign In </h2>
        
            <form action="{% url 'network:login' %}" method="post" class = "card-body">
                {% csrf_token %} 
                {% if message %}
                    <p class="notfound">{{ message }}</p>
                {% endif %}
                <div class = "form-group ">
                    <fieldset>
                        <legend><h3>Enter your username</h3>
                            
                            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
                        </legend>
                    </fieldset>
                </div>
                
                <div class="form-group">          
                    <fieldset>

                        <legend><h3>Enter your password</h3>
                            <input class="form-control" type="password" name="password" placeholder="Password">
                        </legend>
                    </fieldset>
                </div>
            
                <div class="form-group">
                    <input class="btn btn-primary" type="submit" value="Login">
                
                </div>

            </form>
        </legend> 
    </fieldset>
</div>

{% endblock %}

social network app/app/templates/network/network.html
{% extends "network/layout.html" %}

{% block title %}
    Network
{% endblock %}
{%load static %}

{% block body %}

<script>
     var initialsection = "{{request_type}}"


    if (initialsection == ""){
        initialsection = localStorage.getItem('previoussection')
        
    }
    

</script>

<div class="network">

    <nav class="navbar navbar-expand-lg navbar-light bg-light flex-row d-flex bd-highlight mb-3" id ="mini-nav">
        <ul class="navbar-nav">
            <li class="nav-item ">
    
                <button  id ="button" class ="nav-link active" data-section="followers" >Followers </button>
            </li>
            <li class="nav-item">
    
                <button  id ="button" class ="nav-link" data-section="following">Following</button>
            </li>
            <li class="nav-item">
                
                <button  id ="button" class ="nav-link" data-section="suggestions">Suggestions</button>
            </li>
        </ul>
    </nav>
    <section >
    
        <div class ="message">

        </div>
        

        <section>
            <article id ="result">
                
            </article>
        </section>
    

                
</section>

</div>
<script type ="text/javascript" src="{% static 'util.js' %}"></script>
<script type ="text/javascript" src="{% static 'functions.js' %}"></script>
<script type ="text/javascript" src="{% static 'network.js' %}"></script>


     
{% endblock %}

social network app/app/templates/network/newpost.html
{% extends "network/layout.html" %}

{% block title %}
    New Post
{% endblock %}

{% block body %}

<div id ="newpost-div">
    <h2> Write new post</h2>
    <form action="{% url 'network:newpost'  %}" method="POST"  >
        {% csrf_token %}          
        
        {{newpost_form}}
        
            <button type="submit"  name = "newpost" id ="newpost" class="btn btn-primary">Post</button>
        
        
        
    </form> 

</div>
{% endblock %}

social network app/app/templates/network/profile.html
{% extends "network/layout.html" %}

{% block title %}
    Profile
{% endblock %}
{%load static %}

{% block body %}


    <!-- This html page shows current and other user profile     
    1. display all the posts with pagination
    2. user can like any post 
    3. user can edit their own post -->

    <script>
       
        const initialcategory = "{{category}}"
      
    </script>

<script type ="text/javascript" src="{% static 'util.js' %}"></script>
<div id = "profile">
    <div id ="profile-nav">
        <h1>{{username}}</h1>
        



{% if page_info == "current user" %}
        
        <div class ="follow">
                            
            <span ><a href = "{% url 'network:network' request_type='following' %}" id = "following_count" >{{following_count}}  Following</a>  </span> 
            <span ><a href = "{% url 'network:network' request_type='followers' %}" id = "follower_count" >{{follower_count}} Followers</a></span>

        </div>
    </div>
        <hr>
                <!-- profile page of logged in user -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light flex-row d-flex bd-highlight mb-3" id ="mini-nav">
            <ul class="navbar-nav">
                <li class="nav-item ">
 
                    <button  id ="button" class ="nav-link active" data-section="myposts">My Posts </button>
                </li>
                <li class="nav-item">

                    <button  id ="button" class ="nav-link" data-section="networks">My Networks</button>
                </li>
                <li class="nav-item">
                    
                    <button  id ="button" class ="nav-link" data-section="likes">My Likes</button>
                </li>
            </ul>
        </nav>
    
    </div>
    <section>
        <article id ="result">
            
        </article>
    </section>





<script type ="text/javascript" src="{% static 'functions.js' %}"></script>
<script type ="text/javascript" src="{% static 'profile.js' %}"></script>

<script type ="text/javascript" src="{% static 'index.js' %}"></script>


{% else %}
        <div class ="follow">
            <div><span id ="connect"></span></div>
            <span ><a id = "following_count" >{{following_count}}  Following</a>  </span> 
            <span ><a id = "follower_count" >{{follower_count}} Followers</a></span>
        
        </div>
    </div>
    <hr>
    <!-- profile page of other user -->
    <section >
        <article class = "other_profile">
            <div class ="message">

            </div>

            
            <div id ="showposts flex-container"> 
                {% for post in posts %}

                   
                    <div class = "card" id= "post">
                        <span>
                            <h2 id ="post_userid" class="card-title">{{post.user_id}}</h2>
                            <h3 id ="post_content">{{post.contents}}</h3>
                            <h4 id ="post_dateandtime">{{post.date_and_time}}</h4>
                            <h4 class='like'>{{post.num_of_likes}}</h4>
                            {% if post.num_of_likes > 0 and post_liked_ids|length  and post.id in post_liked_ids %}
                        

                                <a id ="like" href = "" data-section = "{{post.id}}"><i class="fa fa-heart" style = "color:#f7786b"></i></a>

                            {% else %}
                                <a id ="like" href = "" data-section = "{{post.id}}"><i class="fa fa-heart" style = "color:#b0aac0"></i></a>
                            
                            {% endif %}
                        </span>
                    </div>
                    {% empty %}
        
                    <h5>No posts</h5>
                {% endfor %}
            </div>
        </article>

    </section>
    <script>
        // follow or unfollow option while displaying other user profile

        connect =  "{{connect}}"
        user_id = "{{other_user_id}}"
        
        loc ="{% url 'network:connect' user=username  %}"
        var form = createForm("post",loc)
        var crsf = formCrsf();
    
        if (connect == "following"){
            var togglebutton = createElement('span',null,null,'<input type= "hidden" class="btn btn-primary" name = "change"  value ='+user_id+' /> <input type= "submit"  class="btn btn-primary" name = "btn"  value =  following />')
            }
            else{
            var togglebutton = createElement('span',null,null,'<input type= "hidden"  class="btn btn-primary" name = "change"  value ='+user_id+' /> <input type= "submit"  class="btn btn-primary" name = "btn"  value =  follow />')
            }
            
        appendChild(parent =form,crsf,togglebutton);
        document.querySelector("#connect").appendChild(form)
        
    
    </script>
{% endif %}


{% endblock %}

social network app/app/templates/network/register.html
{% extends "network/layout.html" %}

{% block title %}
    Profile
{% endblock %}
{%load static %}

{% block body %}


    <!-- This html page shows current and other user profile     
    1. display all the posts with pagination
    2. user can like any post 
    3. user can edit their own post -->

    <script>
       
        const initialcategory = "{{category}}"
      
    </script>

<script type ="text/javascript" src="{% static 'util.js' %}"></script>
<div id = "profile">
    <div id ="profile-nav">
        <h1>{{username}}</h1>
        



{% if page_info == "current user" %}
        
        <div class ="follow">
                            
            <span ><a href = "{% url 'network:network' request_type='following' %}" id = "following_count" >{{following_count}}  Following</a>  </span> 
            <span ><a href = "{% url 'network:network' request_type='followers' %}" id = "follower_count" >{{follower_count}} Followers</a></span>

        </div>
    </div>
        <hr>
                <!-- profile page of logged in user -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light flex-row d-flex bd-highlight mb-3" id ="mini-nav">
            <ul class="navbar-nav">
                <li class="nav-item ">
 
                    <button  id ="button" class ="nav-link active" data-section="myposts">My Posts </button>
                </li>
                <li class="nav-item">

                    <button  id ="button" class ="nav-link" data-section="networks">My Networks</button>
                </li>
                <li class="nav-item">
                    
                    <button  id ="button" class ="nav-link" data-section="likes">My Likes</button>
                </li>
            </ul>
        </nav>
    
    </div>
    <section>
        <article id ="result">
            
        </article>
    </section>





<script type ="text/javascript" src="{% static 'functions.js' %}"></script>
<script type ="text/javascript" src="{% static 'profile.js' %}"></script>

<script type ="text/javascript" src="{% static 'index.js' %}"></script>


{% else %}
        <div class ="follow">
            <div><span id ="connect"></span></div>
            <span ><a id = "following_count" >{{following_count}}  Following</a>  </span> 
            <span ><a id = "follower_count" >{{follower_count}} Followers</a></span>
        
        </div>
    </div>
    <hr>
    <!-- profile page of other user -->
    <section >
        <article class = "other_profile">
            <div class ="message">

            </div>

            
            <div id ="showposts flex-container"> 
                {% for post in posts %}

                   
                    <div class = "card" id= "post">
                        <span>
                            <h2 id ="post_userid" class="card-title">{{post.user_id}}</h2>
                            <h3 id ="post_content">{{post.contents}}</h3>
                            <h4 id ="post_dateandtime">{{post.date_and_time}}</h4>
                            <h4 class='like'>{{post.num_of_likes}}</h4>
                            {% if post.num_of_likes > 0 and post_liked_ids|length  and post.id in post_liked_ids %}
                        

                                <a id ="like" href = "" data-section = "{{post.id}}"><i class="fa fa-heart" style = "color:#f7786b"></i></a>

                            {% else %}
                                <a id ="like" href = "" data-section = "{{post.id}}"><i class="fa fa-heart" style = "color:#b0aac0"></i></a>
                            
                            {% endif %}
                        </span>
                    </div>
                    {% empty %}
        
                    <h5>No posts</h5>
                {% endfor %}
            </div>
        </article>

    </section>
    <script>
        // follow or unfollow option while displaying other user profile

        connect =  "{{connect}}"
        user_id = "{{other_user_id}}"
        
        loc ="{% url 'network:connect' user=username  %}"
        var form = createForm("post",loc)
        var crsf = formCrsf();
    
        if (connect == "following"){
            var togglebutton = createElement('span',null,null,'<input type= "hidden" class="btn btn-primary" name = "change"  value ='+user_id+' /> <input type= "submit"  class="btn btn-primary" name = "btn"  value =  following />')
            }
            else{
            var togglebutton = createElement('span',null,null,'<input type= "hidden"  class="btn btn-primary" name = "change"  value ='+user_id+' /> <input type= "submit"  class="btn btn-primary" name = "btn"  value =  follow />')
            }
            
        appendChild(parent =form,crsf,togglebutton);
        document.querySelector("#connect").appendChild(form)
        
    
    </script>
{% endif %}


{% endblock %}