wiki site/app/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.entry_detail, name="entry_detail"),
    path("search", views.search, name="search"),
    path("create-page", views.create_page, name="create_page"),
    path("edit-page/<str:title>:", views.edit_page, name="edit_page"),
    path("random", views.random_wiki, name="random")
]

wiki site/app/models.py
from django.db import models

# Create your models here.

wiki site/app/views.py
from django.shortcuts import render
from . import util
from django.http import HttpResponseRedirect
from django.urls import reverse
import random

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry_detail(request, entry):
    
    content = util.get_entry(entry)
    content = util.convert(content)
    if content is None:
        return render(request, "encyclopedia/index.html", {
            "error": "ERROR",
            "message": f"The wiki entry for {entry} does not exist."
        })
    else:
        return render(request, "encyclopedia/layout.html", {
            "title": entry,
            "content": content,
            "entries": util.list_entries() 
        })

def search(request):
    if request.method == "POST":
        query = request.POST.get("q", "")
        if query:
            results = []
            entries = util.list_entries()
            for entry in entries:
                if query.lower() == entry.lower():
                    return entry_detail(request, entry)
                if query.lower() in entry.lower():
                    results.append(entry)
            if results:
                return render(request, "encyclopedia/search.html", {
                    "entries" : results
                })
            else:
                return render(request, "encyclopedia/search.html", {
                    "message": f"No wiki entries found for {query}"
                })
    return index(request)

def create_page(request):
    if request.method == "POST":
        title = request.POST.get("title")
        exists = util.get_entry(title)
        body = request.POST.get("body")
        if exists:
            return render(request, "encyclopedia/create_page.html", {
                "error": "Error: Wiki entry already exists"
            })
        util.save_entry(title, body)
        return HttpResponseRedirect(reverse("encyclopedia:entry_detail", args=[title]))
            
    return render(request, "encyclopedia/create_page.html")

def edit_page(request, title):
    if request.method == "POST":
        print(request.POST)
        if request.POST.get("save") == "Save changes":
            body = request.POST.get("body")
            util.save_entry(title, body)
            return HttpResponseRedirect(reverse("encyclopedia:entry_detail", args=[title]))
        elif request.POST.get("edit") == "Edit Page":   
            content = request.POST.get("body")
            return render(request, "encyclopedia/edit_page.html", {
                "content": content,
                "title": title
            })
        
def random_wiki(request):
    titles = util.list_entries()
    title = random.choice(titles)
    return HttpResponseRedirect(reverse("encyclopedia:entry_detail", args=[title]))

wiki site/app/templates/encyclopedia/create_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

    Create New Page

{% endblock %}

{% block body %}

    <h1>Create New Page</h1>
    {% if error %}
        {{ error }}
    {% else %}
        <form action="{% url 'encyclopedia:create_page' %}" method="post">
            {% csrf_token %}
            <input type="text" name="title" placeholder="Title">
            <textarea name="body" placeholder="Body"></textarea>
            <input type="submit" name="save" value="Save">
        </form>
    {% endif %}

{% endblock %}

wiki site/app/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

    Edit {{ title }} Page

{% endblock %}

{% block body %}

    <h1>Edit Page</h1>

    <form action="{% url 'encyclopedia:edit_page' title|urlencode %}" method="post">
        {% csrf_token %}
        <textarea name="body">{{ content }}</textarea>
        <input type="submit" name="save" value="Save changes">
    </form>

{% endblock %}

wiki site/app/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

    {% if error %}
        {{ error }}
    {% else %}
        Encyclopedia
    {% endif %}

{% endblock %}

{% block body %}

    {% if error %}
        {{ error }}
    {% else %}
        <h1>All Pages</h1>
    {% endif %}

    <ul>
        {% if message %}
            {{ message }}
        {% else %}
            {% for entry in entries %}
                <li><a href="{% url 'encyclopedia:entry_detail' entry|urlencode %}">{{ entry }}</a></li>
            {% endfor %}
        {% endif %}
    </ul>

{% endblock %}

wiki site/app/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %} {{ title }} {% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                    {% if content %}
                        {% for entry in entries %}
                            <li><a href="{% url 'encyclopedia:entry_detail' entry|urlencode %}">{{ entry }}</a></li>
                        {% endfor %}
                    {% endif %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                    {{ content|safe }}
                    <form action="{% url 'encyclopedia:edit_page' title|urlencode %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="body" value="{{ content }}">
                        <input type="submit" name="edit" value="Edit Page">
                    </form>
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki site/app/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

    Search

{% endblock %}

{% block body %}

    <h1>Search Results</h1>

    <ul>
        {% if message %}
            {{ message }}
        {% else %}
            {% for entry in entries %}
                <li><a href="{% url 'encyclopedia:entry_detail' entry|urlencode %}">{{ entry }}</a></li>
            {% endfor %}
        {% endif %}
    </ul>

{% endblock %}